---
- name: Compare intended state in NetBox to actual device state and show delta
  hosts: sites_container_lab
  gather_facts: false
  connection: network_cli

  roles:
    - role: actual_state
    - role: intended_state
    - role: compare_state