---
- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Upload via TFTP
      aoscx_command:
        commands:
        - command: 'copy running-config tftp://10.70.128.32/"{{ hostname }}".txt cli'
          prompt:
            - '.*Continue.*'
          answer:
            - y
#
 #   - name: Show images
 #     aoscx_command:
 #       commands: ["show image"]