- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
    ansible_aoscx_rest_version: 10.09
  tasks:
    - name:
        Retrieve all information from the device and save into a variable
        "facts_output".
      aoscx_facts:
      register: facts_output

    - set_fact:
        current_version_primary: "{{facts_output['ansible_facts']['ansible_net_software_images'].primary_image_version}}"

    - set_fact:
        current_version_secondary: "{{facts_output['ansible_facts']['ansible_net_software_images'].secondary_image_version}}"

    - set_fact:
        system_mac: "{{facts_output['ansible_facts']['ansible_net_product_info']['chassis,1'].base_mac_address}}"

    - set_fact:
        interfaces_desc: "{{facts_output['ansible_facts']['ansible_net_interfaces'].description}}"

    - debug:
        var: current_version_primary
    - debug:
        var: current_version_secondary
    - debug:
        var: system_mac
    - debug:
        var: interfaces_desc

