- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
    ansible_aoscx_rest_version: 10.09
  tasks:
    - name: >
        Retrieve all information from the device and save into a variable
        "facts_output".
      aoscx_facts:
      register: facts_output

    - name: Retrieve power supply and domain name info from the device
      aoscx_facts:
      gather_subset:
      - software_info
      - host_name

    - debug:
        var: software_info
    - debug:
        var: shost_name


