- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
    ansible_become_pass: "{{ password }}"
    ansible_become_user: "{{ user }}"  
  tasks:
    - name: Copy Running Config to local storage
      aoscx_backup_config:
        config_name: 'running-config'
        remote_output_file_tftp_path: 'tftp://10.70.128.32/{{hostname}}_config.json'
        config_type: 'json'
        vrf: 'default'
