---
- name: Copy Running Config to local storage with dtm
  hosts: localhost
  tasks:
    - name: Get ansible date/time facts
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    - name: Store DTG as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"
    - name: Create Directory {{hostvars.localhost.DTG}}
      file:
       path: tftp://10.70.128.32/{{hostvars.localhost.DTG}}
       state: directory
   run_once: true
- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
  tasks:
    - name: Copy Running Config to local storage
      aoscx_backup_config: 
        connfig_name: 'running-config'
        remote_output_file_tftp_path: 'tftp://10.70.128.32/{{hostvars.localhost.DTG}}{{ inventory_hostname }}_config.cli'
        config_type: 'cli'
        vrf: 'default'