---
- hosts: all
  connection: local
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: Copy Running Config to TFTP server as Golden Config
      aoscx_backup_config:
        config_name: 'running-config'
        remote_output_file_tftp_path: 'tftp://10.70.128.32/Network_Backups/Bell_Bay_config/golden_config.cli'
        config_type: 'cli'
        vrf: 'mgmt'