---
- hosts: all
  gather_facts: False
  connection: local
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Upload via TFTP
      aoscx_command:
        commands:
        - command: 'copy tftp://10.70.128.32/golden_config.cli'
          prompt:
            - '.*Continue.*'
          answer:
            - y