---
- hosts: all
  gather_facts: False
  connection: local
  collections:
    - arubanetworks.aoscx
  roles:
    - role: arubanetworks.aoscx_role
  vars:
    ansible_connection: network_cli
    ansible_net_user: admin
  tasks:
    - name: Copy Running Config to TFTP server as JSON
      aoscx_backup_config:
        config_name: 'running-config'
        remote_output_file_tftp_path: 'tftp://10.70.128.32/tempconfig.cli'
        config_type: 'cli'
        vrf: 'mgmt'