---
- hosts: all
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: Copy Running Config to local storage
      aoscx_backup_config:
        config_name: 'running-config'
        output_file: '/home/tl_admin/backup_config/running-config.json'
        config_type: 'json'