- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
    ansible_aoscx_rest_version: 10.09
  tasks:
    - name: Set switch ports to facts
      set_fact:
      sw_ports: "{{ sw_ports | default([]) + [item[0] | string] }}" 
      loop: "{{ host_interface_info }}"