- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: true    
  tasks:
    - name: Aruba facts
      aoscx_facts:
        gather_network_resources: ['vlans', 'interfaces']
      register: facts_vlan_output